name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ordinal-cacao-395605
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-python

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: '367.0.0'
          service_account_key: ${{ secrets.RUN_SA_KEY }}

      - name: Build
        run: |
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/${{ secrets.RUN_PROJECT }}/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
